version: '3'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongoDB
    environment:
      MONGODB_URI: ${MONGODB_URI}
    stdin_open: true
    tty: true
    networks:
      - frontend
      - databases

  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/database
    networks:
      - databases
  
networks:
  frontend:
    external: true
  databases:
    driver: bridge