version: '3'

services:
  authentication:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongoDB
      - traefik
    environment:
      MONGODB_URI: ${MONGODB_URI}
    stdin_open: true
    tty: true
    labels:
     - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
    networks:
      - frontend
      - databases

  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/database
    networks:
      - databases
    depends_on:
      - traefik
    labels:
     - "traefik.http.routers.mongo.rule=Host(`mongo.localhost`)"

  traefik:
    image: traefik:v3.0
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  frontend:
    external: true
  databases:
    driver: bridge