version: '3'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      MONGODB_URI: ${MONGODB_URI}
    stdin_open: true
    tty: true
    networks:
      - frontend_backend
      - backend_database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/database
    networks:
      - backend_database
  
networks:
  frontend_backend:
    external: true
  backend_database:
    driver: bridge