version: '3'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:

    environment:
      MONGODB_URI: ${MONGODB_URI} 
    stdin_open: true
    tty: true
    networks:
      - frontend_backend
      - backend_database

  mysql_database:  
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'electiveWeb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - backend_database

  mongo_database: 
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/database
    networks:
      - backend_database

networks:
  frontend_backend:
    external: true
  backend_database:
    driver: bridge
