version: '3'

services:
  authentication:
    build:
      context: ./authentication
    hostname: authentication-service
    ports:
      - "3000:3000"
    depends_on:
      - mongoDB
      - traefik
    env_file:
      - .env
    stdin_open: true
    tty: true
    labels:
     - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
    networks:
      - microservices_network
      - mongodb_network  # À supprimer une fois MySQL installé et fonctionnel
      - mysql_network
  
  monitoring:
    build:
      context: ./monitoring
    hostname: monitoring-service
    ports:
      - "3007:3007"
    depends_on:
      - authentication
      - traefik
    env_file:
      - .env
    stdin_open: true
    tty: true
    labels:
     - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
    networks:
      - microservices_network
      - mongodb_network

  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/database
    depends_on:
      - traefik
    labels:
     - "traefik.http.routers.mongo.rule=Host(`mongo.localhost`)"
    networks:
      - mongodb_network
      - microservices_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_pass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
    networks:
      - mysql_network



  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - "8081:80"


  traefik:
    image: traefik:v3.0
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices_network
  
networks:
  microservices_network:
    driver: bridge
  mongodb_network:
    driver: bridge
  mysql_network:
    driver: bridge

volumes:
  mongodb:
  mysql-data: