api:
  insecure: true
entryPoints:
  web:
    address: ":80"
  frontend:
    address: ":4200"

middlewares:
  strip-prefix:
    stripPrefix:
      prefixes:
        - "/authentication"
        - "/users"
        - "/restaurant"
        - "/menu"
        - "/product"
        - "/order"
        - "/delivery"
        - "/monitoring"
#        - "/components"

http:
  routers:
    authentication-router:
      rule: "Host(`authentication.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: authentication-service
    users-router:
      rule: "Host(`users.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: users-service
    restaurant-router:
      rule: "Host(`restaurant.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: restaurant-service
    menu-router:
      rule: "Host(`menu.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: menu-service
    product-router:
      rule: "Host(`product.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: product-service
    order-router:
      rule: "Host(`order.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: order-service
    delivery-router:
      rule: "Host(`delivery.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: delivery-service
    monitoring-router:
      rule: "Host(`monitoring.localhost`)"
      entryPoints:
        - web
      middlewares:
        - strip-prefix
      service: monitoring-service
#    components-router:
#      rule: "Host(`components.localhost`)"
#      entryPoints:
#        - web
#      middlewares:
#        - strip-prefix
#       service: components-service
    frontend-router:
      rule: "Host(`frontend.localhost`) && PathPrefix(`/`)"
      entryPoints:
        - frontend
      service: frontend

  services:
    authentication-service:
      loadBalancer:
        servers:
          - url: "http://authentication-service:3000"
    users-service:
      loadBalancer:
        servers:
          - url: "http://users-service:3001"
    restaurant-service:
      loadBalancer:
        servers:
          - url: "http://restaurant-service:3002"
    menu-service:
      loadBalancer:
        servers:
          - url: "http://menu-service:3003"
    product-service:
      loadBalancer:
        servers:
          - url: "http://product-service:3004"
    order-service:
      loadBalancer:
        servers:
          - url: "http://order-service:3005"
    delivery-service:
      loadBalancer:
        servers:
          - url: "http://delivery-service:3006"
    monitoring-service:
      loadBalancer:
        servers:
          - url: "http://monitoring-service:3007"
#    components-service:
#      loadBalancer:
#        servers:
#          - url: "http://components-service:${COMPONENT_PORT}"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:4200"