openapi: 3.0.0
info:
  version: 1.0.0
  title: CESI EATS SWAGGER API
  description: |
    Project "Élective Logiciel" - Menu microservice API documentation
servers:
  - url: 'http://localhost:3003'
    description: Development server
paths:
