name: Authentication Service Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  config:
    name: 🛠 🔨 Setup Version
    runs-on: ubuntu-latest
    outputs:
      APP_VERSION: ${{ steps.config.outputs.APP_VERSION }}
      APP_NAME: ${{ steps.config.outputs.APP_NAME }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup version
        id: config
        run: |-
            APP_NAME=$(node -p "require('./authentication/package.json').name")
            APP_VERSION=$(node -p "require('./authentication/package.json').version")
            echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
            echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT

  docker:
    runs-on: ubuntu-latest
    name: 🐋 ☁️ Build Authentication Service
    needs: [config]
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Check directory content
        run: ls -l authentication
      - 
        name: Build and push
        run: docker build -f authentication/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.config.outputs.APP_NAME }}:${{ needs.config.outputs.APP_VERSION }} .
        env:
          DOCKER_BUILDKIT: 1
      - 
        name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.config.outputs.APP_NAME }}:${{ needs.config.outputs.APP_VERSION }}