name: deploy prod

on:
  push:
    branches:
      - main

jobs:

  config:
    name: 🛠 🔨 Setup Version
    runs-on: ubuntu-latest
    outputs:
      APP_VERSION: ${{ steps.config.outputs.APP_VERSION }}
      APP_NAME: ${{ steps.config.outputs.APP_NAME }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup version
        id: config
        run: |-
          APP_NAME=$(node -p "require('./package.json').name")
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "app_name = $APP_NAME"
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "app_version = $APP_VERSION"
          
  docker:
    runs-on: ubuntu-latest
    name: 🐋 ☁️ Build Application
    needs: [ config ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker-compose build
        env:
          DOCKER_BUILDKIT: 1
      -
        name: Tag images
        run: |
          docker tag ${DOCKER_USERNAME}/${{ needs.config.outputs.APP_NAME }}:${{ needs.config.outputs.APP_VERSION }} ${DOCKER_USERNAME}/${{ needs.config.outputs.APP_NAME }}:${{ needs.config.outputs.APP_VERSION }}
          docker push ${DOCKER_USERNAME}/${{ needs.config.outputs.APP_NAME }}:${{ needs.config.outputs.APP_VERSION }}
      -
        name: Push images to Docker Hub
        run: docker-compose push
      -
        name: Tag images as latest
        run: |
          docker tag ${DOCKER_USERNAME}/${{ needs.config.outputs.APP_NAME }}:${{ needs.config.outputs.APP_VERSION }} ${DOCKER_USERNAME}/${{ needs.config.outputs.APP_NAME }}:latest
          docker push ${DOCKER_USERNAME}/${{ needs.config.outputs.APP_NAME }}:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}